=== raulabad-DAW/PROGRAMACION-DAW/LENGUAJE DE MARCAS/RA4-A1-XSD/exemple2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="registros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:integer"></xs:element>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="segundoNombre" type="xs:string" minOccurs="0"></xs:element >
                            <xs:element name="apellido" type="xs:string"></xs:element>
                            <xs:element name="correo" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== raulabad-DAW/PROGRAMACION-DAW/LENGUAJE DE MARCAS/RA4-A1-XSD/exemple2.xml
<?xml version="1.0" encoding="UTF-8"?>
<registros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="exemple2.xsd">
 <usuario>
 <id>101</id>
 <nombre>Eva</nombre>
 <segundoNombre>María</segundoNombre>
 <apellido>Molina</apellido>
 <correo>eva@ejemplo.com</correo>
 </usuario>
 <usuario>
 <id>102</id>
 <nombre>Ana</nombre>
 <apellido>Márquez</apellido>
 <correo>ana@ejemplo.com</correo>
 </usuario>
</registros>
